<div class="top" id="alph">
	<a href="?page=alphabet&letter=А">А</a>
	<a href="?page=alphabet&letter=Б">Б</a>
	<a href="?page=alphabet&letter=В">В</a>
	<a href="?page=alphabet&letter=Г">Г</a>
	<a href="?page=alphabet&letter=Д">Д</a>
	<a href="?page=alphabet&letter=Е">Е</a>
	<a href="?page=alphabet&letter=Ё">Ё</a>
	<a href="?page=alphabet&letter=Ж">Ж</a>
	<a href="?page=alphabet&letter=З">З</a>
	<a href="?page=alphabet&letter=И">И</a>
	<a href="?page=alphabet&letter=Й">Й</a>
	<a href="?page=alphabet&letter=К">К</a>
	<a href="?page=alphabet&letter=Л">Л</a>
	<a href="?page=alphabet&letter=М">М</a>
	<a href="?page=alphabet&letter=Н">Н</a>
	<a href="?page=alphabet&letter=О">О</a>
	<a href="?page=alphabet&letter=П">П</a>
	<a href="?page=alphabet&letter=Р">Р</a>
	<a href="?page=alphabet&letter=С">С</a>
	<a href="?page=alphabet&letter=Т">Т</a>
	<a href="?page=alphabet&letter=У">У</a>
	<a href="?page=alphabet&letter=Ф">Ф</a>
	<a href="?page=alphabet&letter=Х">Х</a>
	<a href="?page=alphabet&letter=Ц">Ц</a>
	<a href="?page=alphabet&letter=Ч">Ч</a>
	<a href="?page=alphabet&letter=Ш">Ш</a>
	<a href="?page=alphabet&letter=Щ">Щ</a>
	<a href="?page=alphabet&letter=Ъ">Ъ</a>
	<a href="?page=alphabet&letter=Ы">Ы</a>
	<a href="?page=alphabet&letter=Ь">Ь</a>
	<a href="?page=alphabet&letter=Э">Э</a>
	<a href="?page=alphabet&letter=Ю">Ю</a>
	<a href="?page=alphabet&letter=Я">Я</a>
|
	<a href="?page=alphabet&letter=A">A</a>
	<a href="?page=alphabet&letter=B">B</a>
	<a href="?page=alphabet&letter=C">C</a>
	<a href="?page=alphabet&letter=D">D</a>
	<a href="?page=alphabet&letter=E">E</a>
	<a href="?page=alphabet&letter=F">F</a>
	<a href="?page=alphabet&letter=G">G</a>
	<a href="?page=alphabet&letter=H">H</a>
	<a href="?page=alphabet&letter=I">I</a>
	<a href="?page=alphabet&letter=G">G</a>
	<a href="?page=alphabet&letter=K">K</a>
	<a href="?page=alphabet&letter=L">L</a>
	<a href="?page=alphabet&letter=M">M</a>
	<a href="?page=alphabet&letter=N">N</a>
	<a href="?page=alphabet&letter=O">O</a>
	<a href="?page=alphabet&letter=P">P</a>
	<a href="?page=alphabet&letter=Q">Q</a>
	<a href="?page=alphabet&letter=R">R</a>
	<a href="?page=alphabet&letter=S">S</a>
	<a href="?page=alphabet&letter=T">T</a>
	<a href="?page=alphabet&letter=U">U</a>
	<a href="?page=alphabet&letter=V">V</a>
	<a href="?page=alphabet&letter=W">W</a>
	<a href="?page=alphabet&letter=X">X</a>
	<a href="?page=alphabet&letter=Y">Y</a>
	<a href="?page=alphabet&letter=Z">Z</a>
|
	<a href="?page=alphabet&letter=0">0</a>
	<a href="?page=alphabet&letter=1">1</a>
	<a href="?page=alphabet&letter=2">2</a>
	<a href="?page=alphabet&letter=3">3</a>
	<a href="?page=alphabet&letter=4">4</a>
	<a href="?page=alphabet&letter=5">5</a>
	<a href="?page=alphabet&letter=6">6</a>
	<a href="?page=alphabet&letter=7">7</a>
	<a href="?page=alphabet&letter=8">8</a>
	<a href="?page=alphabet&letter=9">9</a>
</div>